# Generated by Django 5.2.13 on 2026-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_is_anonymous_room_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='auto_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='reactions_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
